[project]
authors = ["Manish Kumar"]
entry = "main.sw"
license = "Apache-2.0"
name = "fflonk_verifier"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", rev = "0a56930e054e5843ad0aabea7e434b76353241b9" }
