[project]
authors = ["Elena"]
entry = "main.sw"
license = "Apache-2.0"
name = "plonk_verifier"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", rev = "c681835d4427b8c36d9f340c8d4340aaa03591e6" }
sway-ecc = { git = "https://github.com/hashcloak/sway-ecc" }